name: example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  leancode_contracts:
    path: ../../leancode_contracts
  leancode_contracts_generator:
    path: ..
  leancode_pipe: ^2.0.0

dev_dependencies:
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  leancode_lint: ^17.0.0
