name: leancode_contracts_generator
repository: https://github.com/leancodepl/contractsgenerator-dart
description: Dart contracts client generator for a CQRS API.
version: 0.17.1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  args: ^2.7.0
  code_builder: ^4.11.0
  collection: ^1.19.1
  dart_style: ^3.1.1
  fixnum: ^1.1.1
  meta: ^1.16.0
  path: ^1.9.1
  protobuf: ^4.2.0
  recase: ^4.1.0
  yaml: ^3.1.3

dev_dependencies:
  leancode_contracts:
    path: ../leancode_contracts
  leancode_lint: ^17.0.0
  leancode_pipe: ^2.0.0
  test: ^1.26.3

executables:
  leancode_contracts_generator: leancode_contracts_generator
